openapi: 3.0.0
info:
  version: 1.0.0
  title: Aplicación de gestión de monopatines
  description: app orientada al desarrollo en microservicios. la misma desarrolla la situación propuesta por la cátedra (se documentan solo los endpoints de viajes)
  
servers:
  - url:  localhost/api/viajes
  
paths:
  #Endpoints definidos de viajes
  
  /:
    get:
      summary: obtener todos los usuarios
      description: path que retorna la totalidad de los usuarios cargados
      responses:
        '200':
          description: se ha realizado la operación correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/response-usuario"
        '400':
            $ref: "#/components/responses/NotFound"
  
  /añadir/{idUsuario}/{idMonopatin}:
    post:
      summary: agregar un viaje con un usuario y monopatin
      parameters:
      - name: idUsuario
        in: path
        required: true
        schema:
          type: integer
          format: long
      - name: idMonopatin
        in: path
        required: true
        schema:
          type: integer
          format: long
      responses:
        '200':
          description:  la operacion se realizo con exito
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/response-viaje"
        '400':
            $ref: "#/components/responses/NotFound"
            
  /{id}:
    get:
      summary:  obtener un viaje por id
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: long
      responses:
        '200':
          description: la operacion fue realizada con exito
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response-viaje"
        '400':
            $ref: "#/components/responses/NotFound"
  
  /editar/{id}:
    put:
      summary:  actualizar la totalidad de un viaje
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: long
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/viaje"
      responses:
        '200':
          description: la operacion fue realizada con exito
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response-viaje"
        '400':
            $ref: "#/components/responses/NotFound"
   
  /eliminar/{id}:
    delete:
      summary:  eliminar un viaje
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: long
      responses:
        '200':
          description: la operacion fue realizada con exito
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response-viaje"
        '400':
            $ref: '#/components/responses/NotFound'
  
  /pausa/{id}:
    get:
      summary:  obtener la pausa de un monopatin
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: long
      responses:
        '200':
          description: la operacion fue realizada con exito
          content:
            application/json:
              schema:
                type: string
                format: duration
        '400':
            $ref: "#/components/responses/NotFound"
  
  /buscar/cantidadByTiempo:
    get:
      summary:  obtener la cantidad de viajes entre dos fechas
      parameters:
      - name: mesIni
        in: query
        required: true
        schema:
          type: integer
      - name: mesFin
        in: query
        required: true
        schema:
          type: integer
      - name: anio
        in: query
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: la operacion fue realizada con exito
          content:
            application/json:
              schema:
                type: integer
                format: long
        '400':
            $ref: "#/components/responses/NotFound"
  
  /finalizar/{idViaje}:
    patch:
      summary:  finalizar un viaje
      parameters:
      - name: idViaje
        in: path
        required: true
        schema:
          type: integer
      - name: latitud
        in: query
        required: true
        schema:
          type: number
          format: double
      - name: longitud
        in: query
        required: true
        schema:
          type: number
          format: double
      responses:
        '200':
          description:  la operacion se realizo con exito
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/viaje-finalizado"
        '400':
          $ref: '#/components/responses/NotFound'
  
components:
  schemas:
    response-usuario:
      type: object
      properties:
        id:
          type: integer
          format: long
        nombre:
          type: string
        celular:
          type: string
        email:
          type: string
    
    response-viaje:
      type: object
      properties:
        idViaje:
          type: integer
          format: long
        idUsuario:
          type: integer
          format: long
        idMonopatin:
          type: integer
          format: long
        inicio:
          type: string
          format: localdatetime
        mensaje:
          type: string
        exitp:
          type: boolean
    
    viaje:
      type: object
      properties:
        id:
          type: integer
          format: long
        id_usuario:
          type: integer
          format: long
        idMonopatin:
          type: integer
          format: long
        inicio:
          type: string
          format: localdatetime
        finalizacion:
          type: string
          format: localdatetime
        pausa_duracion:
          type: string
          format: duration
        kilometros_recorridos:
          type: integer
    
    viaje-finalizado:
      type: object
      properties:
        idViaje:
          type: integer
          format: long
        inicio:
          type: string
          format: localdatetime
        pausa:
          type: integer
        finalizacion:
          type: string
          format: localdatetime
        costo:
          type: integer
        mensaje:
          type: string
        exito:
          type: boolean
    
  responses:
    ok:
      description:  "la operación se realizó con exito"
    
    NotFound:
      description:  "no se encontró el objeto a modificar"
      
    BadRequest:
      description:  "se ha realizado una petición de manera incorrecta"